spring.application.name=system

spring.datasource.url=jdbc:postgresql://dpg-d8ds9d7avr4c73835tm0-a:5432/hotel_db_yqg6
spring.datasource.username=hotel_db_yqg6_user
spring.datasource.password=8XJqEVHmAF87k4u0UOoluEJ8ruO62gX5
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
server.port=${PORT:8080}

stripe.secret.key=sk_test_51TVCFa2RnAyKx7MqMTFhvqFh3zmDIu7R1S18uQ24Nry4AWQ2DrTJSsPgcsDIu9I5ENwRFQ4Jz3vbhZKbfOVoLCRG00DvuuCZyJ

stripe.publishable.key=sk_test_51TVCFa2RnAyKx7MqMTFhvqFh3zmDIu7R1S18uQ24Nry4AWQ2DrTJSsPgcsDIu9I5ENwRFQ4Jz3vbhZKbfOVoLCRG00DvuuCZyJ



spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=Sivaperumal1278@gmail.com
spring.mail.password=nyzrgnozxybcngxv

spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true